version:     "0018b--03-Aug-2021"
copyright:   "2021-2021"
description:
  This is a
  GitHub Page Operating Systems
disclaimer:
  I have spoken.
keywords:    "jekyll, testing"
navbarlinks:
- navbar:    "Home"
  link:      "/"
- navbar:    "My Log"
  link:      "https://ramdhanfirdaus.github.io/os212/TXT/mylog.txt)"
- navbar:    "Links"
  link:      "/LINKS/"
- navbar:    "GitHub"
  link:      "https://github.com/ramdhanfirdaus/os212"
- navbar:    "TarBall"
  link:      "https://os.vlsm.org/Log/ramdhanfirdaus.tar.bz2.txt"
- navbar:    "Tips"
  link:      "/TIPS/"
- navbar:    "Listing"
  link:      "/000.html"
- navbar:    "About"
  link:      "/ABOUT/"
- navbar:    "GitHub Page"
  link:      "https://ramdhanfirdaus.github.io/os212/"
title:       "GitHub Page Operating Systems"
lang:        "en-US"
author:      "Ramdhan Firdaus Amelia"
address:     "Cirebon, Jawa Barat"
sitemap:     "true"
markdown:    "kramdown"
defaults:
- scope:
    path:    ""
  values:
    layout:  "default"
github:
- metadata
plugins:
- jekyll-sitemap
- jekyll-seo-tag
google_analytics: "UA-89852122-15"

urlweb:           "https://ramdhanfirdaus.github.io/os212/"
urlcontact:       "TBA"
urlgithub:        "https://github.com/ramdhanfirdaus/os212"
